### ISSUE TITLE
DMR Usb Connect

### ISSUE THREAD

**Issue by JarvisSmallhouse** [rick51231/node-dmr-lib#1]
Hi , sorry for the way contact 
i m using  dm3400 usb i would like to pilot it  with web interface (not talk)
i check your research  and found it nice
I would use it with node JS API Rest 
did you ever dialog  throught  usb/IP DMR  ? 

Thanks

**Comment by rick51231** [comment]
Hello

I have plans to make a DMR data modem via raspberry and DP3401 radio, but haven't tried that yet (maybe in next two months).

The basic is to connect via XNL/XCMP (TCP port 8002) and send commands. You will need an auth hash (it's for repeater, should work with the radio?):  https://github.com/rick51231/node-dmr-lib/blob/1ed6db52d5550c6b16f477c7bea14da586849ef6/src/Protocols/XNL.js#L88 
Control packets can be obtained via Wireshark. Try "Radio Front Panel Test harness" from  https://www.transtrbo.com/downloads.php
